// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalWebHooks.Core.DataStore;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(MinimalWebhooksDbContext))]
    [Migration("20230718121216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("MinimalWebHooks.Core.Models.DbSets.WebhookClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebhookClients");
                });

            modelBuilder.Entity("MinimalWebHooks.Core.Models.DbSets.WebhookClientHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WebhookClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebhookClientId");

                    b.ToTable("WebhookClientHeaders");
                });

            modelBuilder.Entity("MinimalWebHooks.Core.Models.DbSets.WebhookClientHeader", b =>
                {
                    b.HasOne("MinimalWebHooks.Core.Models.DbSets.WebhookClient", null)
                        .WithMany("ClientHeaders")
                        .HasForeignKey("WebhookClientId");
                });

            modelBuilder.Entity("MinimalWebHooks.Core.Models.DbSets.WebhookClient", b =>
                {
                    b.Navigation("ClientHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
